// Faculty ID prefixes (165 = STEI)
export const MAJOR_MAPPINGS: Record<string, string> = {
   "101": "Matematika",
  "102": "Fisika",
  "103": "Astronomi",
  "104": "Mikrobiologi",
  "105": "Kimia",
  "106": "Biologi",
  "107": "Sains dan Teknologi Farmasi",
  "108": "Aktuaria",
  "109": "Teknik Oseanografi",
  "112": "Rekayasa Hayati",
  "114": "Rekayasa Pertanian",
  "115": "Rekayasa Kehutanan",
  "116": "Farmasi Klinik dan Komunitas",
  "119": "Teknologi Pasca Panen",
  "120": "Teknik Geologi",
  "121": "Teknik Pertambangan",
  "122": "Teknik Perminyakan",
  "123": "Teknik Geofisika",
  "125": "Teknik Metalurgi",
  "128": "Meteorologi",
  "129": "Oseanografi",
  "130": "Teknik Kimia",
  "131": "Teknik Mesin",
  "132": "Teknik Elektro",
  "133": "Teknik Fisika",
  "134": "Teknik Industri",
  "135": "Teknik Informatika",
  "136": "Aeronotika dan Astronotika",
  "137": "Teknik Material",
  "143": "Teknik Pangan",
  "144": "Manajemen Rekayasa Industri",
  "145": "Teknik Bioenergi dan Kemurgi",
  "150": "Teknik Sipil",
  "151": "Teknik Geodesi dan Geomatika",
  "152": "Arsitektur",
  "153": "Teknik Lingkungan",
  "154": "Perencanaan Wilayah dan Kota",
  "155": "Teknik Kelautan",
  "157": "Rekayasa Infrastruktur Lingkungan",
  "158": "Teknik dan Pengelolaan Sumber Daya Air",
  "160": "FMIPA",
  "161": "SITH - Sains",
  "162": "SF",
  "163": "FITB",
  "164": "FTTM",
  "165": "STEI - Rekayasa",
  "166": "FTSL",
  "167": "FTI",
  "168": "FSRD",
  "169": "FTMD",
  "170": "Seni Rupa",
  "171": "Desain",
  "172": "Kriya",
  "173": "Desain Interior",
  "174": "Desain Komunikasi Visual",
  "175": "Desain Produk",
  "180": "Teknik Tenaga Listrik",
  "181": "Teknik Telekomunikasi",
  "182": "Sistem Teknologi dan Informasi",
  "183": "Teknik Biomedis",
  "190": "Manajemen",
  "192": "Kewirausahaan",
  "196": "STEI - Komputasi",
  "197": "SBM",
  "198": "SITH - Rekayasa",
  "199": "SAPPK",
  "201": "Matematika",
  "202": "Fisika",
  "203": "Astronomi",
  "205": "Kimia",
  "206": "Biologi",
  "207": "Farmasi",
  "208": "Aktuaria",
  "209": "Sains Komputasi",
  "211": "Bioteknologi",
  "213": "Biomanajemen",
  "220": "Teknik Geologi",
  "221": "Rekayasa Pertambangan",
  "222": "Teknik Perminyakan",
  "223": "Teknik Geofisika",
  "224": "Sains Kebumian",
  "225": "Teknik Metalurgi",
  "226": "Teknik Panas Bumi",
  "227": "Teknik Air Tanah",
  "230": "Teknik Kimia",
  "231": "Teknik Mesin",
  "232": "Teknik Elektro",
  "233": "Teknik Fisika",
  "234": "Teknik dan Manajemen Industri",
  "235": "Informatika",
  "236": "Aeronotika dan Astronotika",
  "237": "Ilmu dan Teknik Material",
  "238": "Instrumentasi dan Kontrol",
  "239": "Studi Pertahanan",
  "240": "Studi Pembangunan",
  "242": "Transportasi",
  "249": "Ilmu dan Rekayasa Nuklir",
  "250": "Teknik Sipil",
  "251": "Teknik Geodesi dan Geomatika",
  "252": "Arsitektur",
  "253": "Teknik Lingkungan",
  "254": "Perencanaan Wilayah dan Kota",
  "255": "Teknik Kelautan",
  "256": "Rancang Kota",
  "269": "Sistem dan Teknik Jalan Raya",
  "270": "Seni Rupa",
  "271": "Desain",
  "289": "Arsitektur Lanskap",
  "290": "Sains Manajemen",
  "291": "Administrasi Bisnis",
  "301": "Matematika",
  "302": "Fisika",
  "303": "Astronomi",
  "305": "Kimia",
  "306": "Biologi",
  "307": "Farmasi",
  "320": "Teknik Geologi",
  "321": "Rekayasa Pertambangan",
  "322": "Teknik Perminyakan",
  "323": "Teknik Geofisika",
  "324": "Sains Kebumian",
  "330": "Teknik Kimia",
  "331": "Teknik Mesin",
  "332": "Teknik Elektro dan Informatika",
  "333": "Teknik Fisika",
  "334": "Teknik dan Manajemen Industri",
  "336": "Aeronotika dan Astronotika",
  "337": "Ilmu dan Teknik Material",
  "342": "Transportasi",
  "349": "Rekayasa Nuklir",
  "350": "Teknik Sipil",
  "351": "Teknik Geodesi dan Geomatika",
  "352": "Arsitektur",
  "353": "Teknik Lingkungan",
  "354": "Perencanaan Wilayah dan Kota",
  "370": "Ilmu Seni Rupa dan Desain",
  "371": "Desain",
  "390": "Sains Manajemen",
  "901": "Pengajaran Matematika",
  "902": "Pengajaran Fisika",
  "905": "Pengajaran Kimia",
  "907": "Profesi Apoteker",
  "950": "Pengelolaan Sumberdaya Air (PSDA)",
  "957": "Terapan Perencanaan Kepariwisataan",
};

export function inferMajorName(facultyId: string, majorId?: string): string {
  // Try to get major name from majorId first
  if (majorId) {
    const majorPrefix = majorId.substring(0, 3);
    if (majorPrefix in MAJOR_MAPPINGS) {
      return MAJOR_MAPPINGS[majorPrefix];
    }
  }

  // Fallback to faculty name if no major match
  const facultyPrefix = facultyId.substring(0, 3);
  if (facultyPrefix in MAJOR_MAPPINGS) {
    return MAJOR_MAPPINGS[facultyPrefix];
  }

  // Return Unknown if no match found
  return 'Unknown Major';
}